name: edu_share
description: "A new Flutter project."
version: 1.0.0+1
environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.14.0
  shared_preferences: ^2.5.3
  cached_network_image: ^3.4.1
  flutter_svg: ^2.2.0
  stacked: ^3.4.4
  firebase_auth: ^5.6.0
  firebase_storage: ^12.4.7
  cloud_firestore: ^5.6.9
  shimmer: ^3.0.0
  file_picker: ^10.2.0
  image_picker: ^1.1.2
  delightful_toast: ^1.1.0

flutter_icons:
  android: "launcher_icon"
  # ios: true
  image_path: "assets/images/logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
  - assets/images/
  - assets/icons/
  

  fonts:
    - family: SFProText
      fonts:
        - asset: fonts/SF-Pro-Text-Black.otf
          weight: 900
        - asset: fonts/SF-Pro-Text-BlackItalic.otf
          weight: 900
          style: italic
        - asset: fonts/SF-Pro-Text-Bold.otf
          weight: 700
        - asset: fonts/SF-Pro-Text-BoldItalic.otf
          weight: 700
          style: italic
        - asset: fonts/SF-Pro-Text-Heavy.otf
          weight: 800
        - asset: fonts/SF-Pro-Text-HeavyItalic.otf
          weight: 800
          style: italic
        - asset: fonts/SF-Pro-Text-Light.otf
          weight: 300
        - asset: fonts/SF-Pro-Text-LightItalic.otf
          weight: 300
          style: italic
        - asset: fonts/SF-Pro-Text-Medium.otf
          weight: 500
        - asset: fonts/SF-Pro-Text-MediumItalic.otf
          weight: 500
          style: italic
        - asset: fonts/SF-Pro-Text-Regular.otf
          weight: 400
        - asset: fonts/SF-Pro-Text-RegularItalic.otf
          weight: 400
          style: italic
        - asset: fonts/SF-Pro-Text-Semibold.otf
          weight: 600
        - asset: fonts/SF-Pro-Text-SemiboldItalic.otf
          weight: 600
          style: italic
        - asset: fonts/SF-Pro-Text-Thin.otf
          weight: 100
        - asset: fonts/SF-Pro-Text-ThinItalic.otf
          weight: 100
          style: italic
        - asset: fonts/SF-Pro-Text-Ultralight.otf
          weight: 200
        - asset: fonts/SF-Pro-Text-UltralightItalic.otf
          weight: 200
          style: italic

 
