// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAU-CiUIfrTfVwzTa7f5-cm0WmDZitZ5as',
    appId: '1:70281911321:web:9f9c6db333556ff7aade88',
    messagingSenderId: '70281911321',
    projectId: 'edushare-3c3c9',
    authDomain: 'edushare-3c3c9.firebaseapp.com',
    storageBucket: 'edushare-3c3c9.firebasestorage.app',
    measurementId: 'G-67HRLHSHPL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-yN8W8MrDvMczo4SiQ0nlQVrGLvPgIRE',
    appId: '1:70281911321:android:75fc45a702cfe588aade88',
    messagingSenderId: '70281911321',
    projectId: 'edushare-3c3c9',
    storageBucket: 'edushare-3c3c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqf336vkbCmxTXPm9yMto4332fVlpVbqk',
    appId: '1:70281911321:ios:5bd3934c3463fe21aade88',
    messagingSenderId: '70281911321',
    projectId: 'edushare-3c3c9',
    storageBucket: 'edushare-3c3c9.firebasestorage.app',
    iosBundleId: 'com.example.eduShare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqf336vkbCmxTXPm9yMto4332fVlpVbqk',
    appId: '1:70281911321:ios:5bd3934c3463fe21aade88',
    messagingSenderId: '70281911321',
    projectId: 'edushare-3c3c9',
    storageBucket: 'edushare-3c3c9.firebasestorage.app',
    iosBundleId: 'com.example.eduShare',
  );
}
